#!/usr/bin/env python3
"""
Terraform to Ansible Inventory Bridge - Student Edition
Reads Terraform outputs and generates Ansible inventory file.
"""

import json
import sys
import subprocess
from pathlib import Path

def main():
    if len(sys.argv) < 3:
        print("Usage: python3 terraform_to_ansible.py <terraform-dir> <output-file>")
        sys.exit(1)
    
    terraform_dir = sys.argv[1]
    output_file = sys.argv[2]
    
    try:
        # Get Terraform outputs
        result = subprocess.run(
            ["terraform", "output", "-json"],
            cwd=terraform_dir,
            capture_output=True,
            text=True,
            timeout=30
        )
        
        if result.returncode != 0:
            print(f"Error: {result.stderr}", file=sys.stderr)
            sys.exit(1)
        
        outputs = json.loads(result.stdout)
        
        # Generate inventory
        inventory_lines = ["# Auto-generated by terraform_to_ansible.py", ""]
        inventory_lines.append("[jenkins_servers]")
        
        # Extract instances from Terraform output
        if "instances_with_ssh" in outputs:
            instances = outputs["instances_with_ssh"]["value"].get("instances", [])
            for instance in instances:
                line = f"{instance['name']} ansible_host={instance['ansible_host']} ansible_user={instance['ansible_user']}"
                inventory_lines.append(line)
        
        inventory_lines.append("")
        inventory_lines.append("[jenkins_servers:vars]")
        inventory_lines.append("ansible_python_interpreter=/usr/bin/python3")
        inventory_lines.append("ansible_connection=ssh")
        inventory_lines.append("ansible_port=22")
        inventory_lines.append("ansible_ssh_common_args='-o StrictHostKeyChecking=no'")
        
        # Save inventory
        Path(output_file).parent.mkdir(parents=True, exist_ok=True)
        with open(output_file, 'w') as f:
            f.write("\n".join(inventory_lines))
        
        print(f"✓ Inventory generated: {output_file}")
        
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    main()
